name: "Beszel Hub"
description: "Lightweight server monitoring hub with Docker stats and historical data"
version: "0.2.0"
slug: "beszel_hub"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
hassio_api: true
hassio_role: default
ports:
  8090/tcp: 8090
webui: "http://[HOST]:[PORT:8090]"
ingress: true
ingress_port: 8090
panel_icon: mdi:chart-line
ports_description:
  8090/tcp: "Web interface and API"
options:
  user_email: ""
  user_password: ""
  app_url: ""
  disable_password_auth: false
  share_all_systems: false
  auto_login: ""
schema:
  user_email: str?
  user_password: password?
  app_url: str?
  disable_password_auth: bool?
  share_all_systems: bool?
  auto_login: email?
  csp: str?
  mfa_otp: list(false|true|superusers)?
  trusted_auth_header: str?
  user_creation: bool?
environment:
  LOG_LEVEL: info
