name: "Beszel Hub"
description: "Lightweight server monitoring hub with Docker stats and historical data"
version: "0.1.0"
slug: "beszel_hub"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
hassio_api: true
hassio_role: default
ports:
  8090/tcp: 8090
webui: "http://[HOST]:[PORT:8090]"
ingress: true
ingress_port: 8090
panel_icon: mdi:chart-line
ports_description:
  8090/tcp: "Web interface and API"
