name: "Beszel Hub"
version: "0.7.0"
slug: "beszel-hub"
description: "Lightweight server monitoring hub with Docker statistics, historical data, and alerts"
arch:
  - aarch64
  - amd64
  - armv7
url: "https://github.com/anand34577/homeassistant-beszel-hub"
init: false
startup: services
boot: auto
hassio_api: true
hassio_role: default
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: "Web UI port"
ingress: true
ingress_port: 8090
panel_icon: mdi:monitor-dashboard
webui: "http://[HOST]:[PORT:8090]"
map:
  - config:rw
environment:
  BESZEL_DATA_DIR: "/config/beszel_data"
options:
  BESZEL_HUB_APP_URL: ""
  BESZEL_HUB_AUTO_LOGIN: ""
  BESZEL_HUB_CSP: ""
  BESZEL_HUB_DISABLE_PASSWORD_AUTH: "false"
  BESZEL_HUB_MFA_OTP: ""
  BESZEL_HUB_SHARE_ALL_SYSTEMS: "false"
  BESZEL_HUB_TRUSTED_AUTH_HEADER: ""
  BESZEL_HUB_USER_CREATION: "false"
  BESZEL_HUB_USER_EMAIL: ""
  BESZEL_HUB_USER_PASSWORD: ""
schema:
  BESZEL_HUB_APP_URL: str?
  BESZEL_HUB_AUTO_LOGIN: str?
  BESZEL_HUB_CSP: str?
  BESZEL_HUB_DISABLE_PASSWORD_AUTH: str?
  BESZEL_HUB_MFA_OTP: str?
  BESZEL_HUB_SHARE_ALL_SYSTEMS: str?
  BESZEL_HUB_TRUSTED_AUTH_HEADER: str?
  BESZEL_HUB_USER_CREATION: str?
  BESZEL_HUB_USER_EMAIL: str?
  BESZEL_HUB_USER_PASSWORD: password?
image: "henrygd/beszel:0.7.0"
