name: Beszel Hub
version: "0.1.0"
slug: beszel-hub
description: Lightweight server monitoring hub with Docker and system stats
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://beszel.dev
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Web interface
environment:
  TZ: Asia/Kolkata
options:
  app_url: ""
  auto_login: ""
  csp: ""
  disable_password_auth: false
  mfa_otp: false
  share_all_systems: false
  trusted_auth_header: ""
  user_creation: false
  user_email: ""
  user_password: ""
schema:
  app_url: str?
  auto_login: email?
  csp: str?
  disable_password_auth: bool
  mfa_otp: "list(false|true|superusers)"
  share_all_systems: bool
  trusted_auth_header: str?
  user_creation: bool
  user_email: email?
  user_password: password?
